from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from app.core.database import get_db
from app.schemas.schemas import DocumentationResponse, DocumentationVersionList
from app.core.logger import logger

router = APIRouter()


@router.get("/{repo_id}", response_model=DocumentationResponse)
async def get_latest_documentation(repo_id: str, db = Depends(get_db)):
    """
    Get latest documentation for a repository
    """
    # Check if repository exists
    repo_response = db.table("repositories").select("id").eq("id", repo_id).execute()
    if not repo_response.data:
        raise HTTPException(status_code=404, detail="Repository not found")
    
    # Get latest documentation
    response = db.table("documentation").select("*").eq("repo_id", repo_id).order("version", desc=True).limit(1).execute()
    
    if not response.data:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    return response.data[0]


@router.get("/{repo_id}/versions", response_model=DocumentationVersionList)
async def get_documentation_versions(
    repo_id: str,
    skip: int = 0,
    limit: int = 10,
    db = Depends(get_db)
):
    """
    Get all documentation versions for a repository
    """
    response = db.table("documentation").select("*", count="exact").eq("repo_id", repo_id).order("version", desc=True).range(skip, skip + limit - 1).execute()
    
    versions = response.data
    total = response.count or 0
    
    return DocumentationVersionList(
        versions=versions,
        total=total
    )


@router.get("/{repo_id}/export/markdown")
async def export_markdown(repo_id: str, db = Depends(get_db)):
    """
    Export documentation as Markdown
    """
    response = db.table("documentation").select("*").eq("repo_id", repo_id).order("version", desc=True).limit(1).execute()
    
    if not response.data:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    doc = response.data[0]
    
    # Get repository info
    repo_response = db.table("repositories").select("*").eq("id", repo_id).execute()
    repo = repo_response.data[0]
    
    # Generate Markdown
    content = doc['content']
    markdown = f"""# {repo['name']}

{content.get('executive_summary', '')}

## Product Overview

{content.get('product_overview', '')}

## Key Features

{chr(10).join(f"- {feature}" for feature in content.get('key_features', []))}

## Technology Stack

### Languages
{', '.join(content.get('tech_stack', {}).get('languages', []))}

### Frameworks
{', '.join(content.get('tech_stack', {}).get('frameworks', []))}

### Databases
{', '.join(content.get('tech_stack', {}).get('databases', []))}

## Architecture

```mermaid
{content.get('architecture', '')}
```

## Use Cases

{chr(10).join(f"{i+1}. {uc}" for i, uc in enumerate(content.get('use_cases', [])))}

## Integrations

{chr(10).join(f"- {integration}" for integration in content.get('integrations', []))}

## Marketing Talking Points

{chr(10).join(f"- {point}" for point in content.get('marketing_points', []))}

---

*Generated by RepoDocAgent*
*Repository: {repo['url']}*
*Commit: {doc['commit_hash']}*
*Files Analyzed: {doc['file_count']}*
*Lines of Code: {doc['lines_of_code']}*
"""
    
    filename = f"{repo['name']}_documentation.md" if repo['name'] else "documentation.md"
    
    return Response(
        content=markdown,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )


@router.get("/{repo_id}/export/json")
async def export_json(repo_id: str, db = Depends(get_db)):
    """
    Export documentation as JSON
    """
    response = db.table("documentation").select("*").eq("repo_id", repo_id).order("version", desc=True).limit(1).execute()
    
    if not response.data:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    doc = response.data[0]
    
    repo_response = db.table("repositories").select("*").eq("id", repo_id).execute()
    repo = repo_response.data[0]
    
    export_data = {
        "repository": {
            "name": repo['name'],
            "url": repo['url'],
            "description": repo['description']
        },
        "documentation": doc['content'],
        "metadata": {
            "version": doc['version'],
            "commit_hash": doc['commit_hash'],
            "file_count": doc['file_count'],
            "lines_of_code": doc['lines_of_code'],
            "generated_at": doc['created_at']
        }
    }
    
    return export_data

