from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.schemas.schemas import DocumentationResponse, DocumentationVersionList
from app.models.models import Documentation, Repository
from app.core.logger import logger

router = APIRouter()


@router.get("/{repo_id}", response_model=DocumentationResponse)
async def get_latest_documentation(repo_id: str, db: Session = Depends(get_db)):
    """
    Get latest documentation for a repository
    """
    # Check if repository exists
    repo = db.query(Repository).filter(Repository.id == repo_id).first()
    if not repo:
        raise HTTPException(status_code=404, detail="Repository not found")
    
    # Get latest documentation
    doc = db.query(Documentation).filter(
        Documentation.repo_id == repo_id
    ).order_by(Documentation.version.desc()).first()
    
    if not doc:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    return doc


@router.get("/{repo_id}/versions", response_model=DocumentationVersionList)
async def get_documentation_versions(
    repo_id: str,
    skip: int = 0,
    limit: int = 10,
    db: Session = Depends(get_db)
):
    """
    Get all documentation versions for a repository
    """
    versions = db.query(Documentation).filter(
        Documentation.repo_id == repo_id
    ).order_by(Documentation.version.desc()).offset(skip).limit(limit).all()
    
    total = db.query(Documentation).filter(
        Documentation.repo_id == repo_id
    ).count()
    
    return DocumentationVersionList(
        versions=versions,
        total=total
    )


@router.get("/{repo_id}/export/markdown")
async def export_markdown(repo_id: str, db: Session = Depends(get_db)):
    """
    Export documentation as Markdown
    """
    doc = db.query(Documentation).filter(
        Documentation.repo_id == repo_id
    ).order_by(Documentation.version.desc()).first()
    
    if not doc:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    # Get repository info
    repo = db.query(Repository).filter(Repository.id == repo_id).first()
    
    # Generate Markdown
    content = doc.content
    markdown = f"""# {repo.name}

{content.get('executive_summary', '')}

## Product Overview

{content.get('product_overview', '')}

## Key Features

{chr(10).join(f"- {feature}" for feature in content.get('key_features', []))}

## Technology Stack

### Languages
{', '.join(content.get('tech_stack', {}).get('languages', []))}

### Frameworks
{', '.join(content.get('tech_stack', {}).get('frameworks', []))}

### Databases
{', '.join(content.get('tech_stack', {}).get('databases', []))}

## Architecture

```mermaid
{content.get('architecture', '')}
```

## Use Cases

{chr(10).join(f"{i+1}. {uc}" for i, uc in enumerate(content.get('use_cases', [])))}

## Integrations

{chr(10).join(f"- {integration}" for integration in content.get('integrations', []))}

## Marketing Talking Points

{chr(10).join(f"- {point}" for point in content.get('marketing_points', []))}

---

*Generated by RepoDocAgent*
*Repository: {repo.url}*
*Commit: {doc.commit_hash}*
*Files Analyzed: {doc.file_count}*
*Lines of Code: {doc.lines_of_code}*
"""
    
    return Response(
        content=markdown,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f"attachment; filename={repo.name}_documentation.md"
        }
    )


@router.get("/{repo_id}/export/json")
async def export_json(repo_id: str, db: Session = Depends(get_db)):
    """
    Export documentation as JSON
    """
    doc = db.query(Documentation).filter(
        Documentation.repo_id == repo_id
    ).order_by(Documentation.version.desc()).first()
    
    if not doc:
        raise HTTPException(status_code=404, detail="Documentation not found")
    
    repo = db.query(Repository).filter(Repository.id == repo_id).first()
    
    export_data = {
        "repository": {
            "name": repo.name,
            "url": repo.url,
            "description": repo.description
        },
        "documentation": doc.content,
        "metadata": {
            "version": doc.version,
            "commit_hash": doc.commit_hash,
            "file_count": doc.file_count,
            "lines_of_code": doc.lines_of_code,
            "generated_at": doc.created_at.isoformat()
        }
    }
    
    return export_data
